"""Markdown report rendering."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd

from alphalab_agent.config import ResearchConfig
from alphalab_agent.review.checks import ReviewCheck, summarize_review


def render_markdown_report(
    config: ResearchConfig,
    metrics: dict[str, float | int],
    data_quality: object,
    factor_ic: pd.DataFrame,
    factor_diagnostics: pd.DataFrame,
    quantile_returns: pd.DataFrame,
    benchmark_comparison: pd.DataFrame,
    benchmark_metrics: pd.DataFrame,
    walk_forward_validation: pd.DataFrame,
    walk_forward_weights: pd.DataFrame,
    supervised_model: dict[str, object],
    ml_oos_evaluation: pd.DataFrame,
    sensitivity_analysis: pd.DataFrame,
    manifest_path: Path | None,
    checks: Iterable[ReviewCheck],
    portfolio_returns: pd.DataFrame,
    positions: pd.DataFrame,
) -> str:
    """Render a deterministic Markdown research report."""

    checks = list(checks)
    data_description = _data_description(config.data_source)
    if config.data_source == "synthetic":
        dataset_limit = "- The dataset is synthetic and is designed for reproducibility, not real alpha discovery."
    else:
        dataset_limit = "- The dataset comes from an explicitly selected adapter and still requires independent validation."
    lines = [
        "# AlphaLab Agent v0.10 Research Report",
        "",
        "## Summary",
        "",
        f"This report was generated by deterministic local code using {data_description}.",
        "It is for engineering demonstration and education only, not investment advice.",
        "",
        f"- Reviewer status: **{summarize_review(checks)}**",
        f"- Rebalance periods: {int(metrics['periods'])}",
        f"- Total return: {_pct(metrics['total_return'])}",
        f"- Annualized return: {_pct(metrics['annualized_return'])}",
        f"- Annualized volatility: {_pct(metrics['annualized_volatility'])}",
        f"- Sharpe: {float(metrics['sharpe']):.2f}",
        f"- Max drawdown: {_pct(metrics['max_drawdown'])}",
        f"- Win rate: {_pct(metrics['win_rate'])}",
        f"- Average turnover: {_pct(metrics['average_turnover'])}",
        f"- Average cost drag: {_pct(metrics['average_cost_drag'])}",
        f"- Total cost drag: {_pct(metrics['total_cost_drag'])}",
        "",
        "## Workflow",
        "",
        f"{data_description} -> panel builder -> factor calculation -> forward return label -> "
        "data quality -> factor diagnostics -> execution backtest -> benchmark comparison -> "
        "robustness -> optional supervised model -> reviewer -> report",
        "",
        "## Research Hypothesis",
        "",
        "A simple composite of momentum, short-horizon reversal, low volatility, and volume trend "
        "can rank the configured stock universe for a deterministic top-k long-only research demo.",
        "",
        "## Data Summary",
        "",
        "| Item | Value |",
        "|---|---:|",
        f"| Data source | `{config.data_source}` |",
        f"| Random seed | `{config.seed}` |",
        f"| Start date | `{config.start_date}` |",
        f"| Business days | `{config.n_days}` |",
        f"| Symbols | `{config.n_symbols}` |",
        f"| Forward label horizon | `{config.forward_days}` days |",
        "",
        "## Data Quality",
        "",
        _dict_to_markdown(getattr(data_quality, "summary", {})),
        "",
        "### Data Quality Issues",
        "",
        _frame_to_markdown(_quality_issues_to_frame(data_quality)),
        "",
        "## Backtest Assumptions",
        "",
        "- v0.10 defaults to execution-based signal-to-portfolio backtesting.",
        "- Signal dates use scores available on that date.",
        "- Portfolio returns start from the next realized daily return after each signal date.",
        "- Forward return labels remain available for IC / RankIC and quantile analysis, not as the default backtest return source.",
        "",
        "## Factor Summary",
        "",
        "| Factor | Weight | Interpretation |",
        "|---|---:|---|",
        f"| momentum_20 | {config.factor_weights.get('momentum_20', 0.0):.2f} | 20-day price momentum |",
        f"| reversal_5 | {config.factor_weights.get('reversal_5', 0.0):.2f} | 5-day mean reversion proxy |",
        f"| low_volatility_20 | {config.factor_weights.get('low_volatility_20', 0.0):.2f} | preference for lower recent volatility |",
        f"| volume_trend_20 | {config.factor_weights.get('volume_trend_20', 0.0):.2f} | 20-day volume trend |",
        "",
        "## Backtest Config",
        "",
        "| Item | Value |",
        "|---|---:|",
        f"| Portfolio rule | `top-{config.top_k} long-only equal weight` |",
        f"| Rebalance interval | `{config.rebalance_every}` business days |",
        f"| Transaction cost | `{config.transaction_cost_bps}` bps per one-way turnover |",
        f"| Annualization | `{config.annualization}` trading days |",
        f"| Backtest mode | `{config.backtest_mode}` |",
        f"| Weighting mode | `{config.weighting_mode}` |",
        "",
        "## Risk Metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Periods | {int(metrics['periods'])} |",
        f"| Total return | {_pct(metrics['total_return'])} |",
        f"| Annualized return | {_pct(metrics['annualized_return'])} |",
        f"| Annualized volatility | {_pct(metrics['annualized_volatility'])} |",
        f"| Sharpe | {float(metrics['sharpe']):.2f} |",
        f"| Max drawdown | {_pct(metrics['max_drawdown'])} |",
        f"| Win rate | {_pct(metrics['win_rate'])} |",
        f"| Average turnover | {_pct(metrics['average_turnover'])} |",
        f"| Average cost drag | {_pct(metrics['average_cost_drag'])} |",
        f"| Total cost drag | {_pct(metrics['total_cost_drag'])} |",
        "",
        "## Factor IC / RankIC Summary",
        "",
        _frame_to_markdown(factor_ic),
        "",
        "## Factor Diagnostics",
        "",
        _frame_to_markdown(factor_diagnostics),
        "",
        "## Quantile Return Analysis",
        "",
        _frame_to_markdown(quantile_returns),
        "",
        "## Benchmark Comparison",
        "",
        _frame_to_markdown(benchmark_comparison),
        "",
        "## Benchmark Metrics",
        "",
        _frame_to_markdown(benchmark_metrics),
        "",
        "## Walk-Forward Validation",
        "",
        _frame_to_markdown(walk_forward_validation),
        "",
        "## Walk-forward Factor Weights",
        "",
        _frame_to_markdown(walk_forward_weights),
        "",
        "## Supervised Factor Model",
        "",
        _dict_to_markdown(supervised_model),
        "",
        "## Out-of-sample ML Evaluation",
        "",
        _frame_to_markdown(ml_oos_evaluation),
        "",
        "## Parameter Sensitivity",
        "",
        _frame_to_markdown(sensitivity_analysis),
        "",
        "## Run Manifest",
        "",
        f"`{_display_path(manifest_path)}`" if manifest_path is not None else "_Manifest generation disabled._",
        "",
        "## Configuration",
        "",
        "| Parameter | Value |",
        "|---|---:|",
    ]

    for key, value in config.to_dict().items():
        lines.append(f"| `{key}` | `{value}` |")

    lines.extend(
        [
            "",
            "## Reviewer Findings",
            "",
            "FAIL is reserved for structural validity or pipeline issues; WARN flags research quality risks such as weak factors, benchmark underperformance, turnover, drawdown, or cost drag.",
            "",
            "| Check | Status | Severity | Message |",
            "|---|---|---|---|",
        ]
    )
    for check in checks:
        lines.append(f"| {check.name} | {check.status} | {check.severity} | {check.message} |")

    lines.extend(["", "## Recent Portfolio Returns", ""])
    lines.append(_frame_to_markdown(portfolio_returns.tail(10)))
    lines.extend(["", "## Recent Positions", ""])
    lines.append(_frame_to_markdown(positions.tail(15)))
    lines.extend(
        [
            "",
            "## Limitations",
            "",
            dataset_limit,
            "- The execution backtest is still a research simulator, not a production execution engine.",
            "- High turnover can make a strategy fragile after realistic costs and constraints.",
            "- v0.10 validation is a lightweight deterministic check, not production-grade model validation.",
            "- Supervised model results are train-only research diagnostics, not production predictions.",
            "",
            "## Safety Notes",
            "",
            "- v0.10 does not use real market data APIs by default.",
            "- v0.10 does not use an LLM by default.",
            "- v0.10 does not place orders or connect to a broker.",
            "- Results do not imply real-world tradability.",
            "",
            "## Disclaimer",
            "",
            "This report is for engineering demonstration and education only. It is not investment "
            "advice and should not be used to make trading decisions.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_markdown_report(path: Path, markdown: str) -> Path:
    """Write a Markdown report and return the path."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    return path


def _pct(value: float | int) -> str:
    return f"{float(value):.2%}"


def _data_description(data_source: str) -> str:
    descriptions = {
        "synthetic": "synthetic market data",
        "csv": "explicit local CSV market data",
        "yfinance": "explicit yfinance market data",
    }
    return descriptions.get(data_source, f"explicit {data_source} market data")


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(Path.cwd().resolve()).as_posix()
    except ValueError:
        return path.name


def _frame_to_markdown(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "_No rows produced._"
    display = frame.copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(lambda value: f"{value:.6f}")
    display = display.astype(str)
    header = "| " + " | ".join(display.columns) + " |"
    separator = "| " + " | ".join("---" for _ in display.columns) + " |"
    rows = ["| " + " | ".join(row) + " |" for row in display.to_numpy()]
    return "\n".join([header, separator, *rows])


def _dict_to_markdown(data: dict[str, object]) -> str:
    if not data:
        return "_No structured summary produced._"
    rows = []
    for key, value in data.items():
        rows.append({"item": key, "value": value})
    return _frame_to_markdown(pd.DataFrame(rows))


def _quality_issues_to_frame(data_quality: object) -> pd.DataFrame:
    issues = getattr(data_quality, "issues", [])
    rows = []
    for issue in issues:
        if hasattr(issue, "to_dict"):
            rows.append(issue.to_dict())
        elif isinstance(issue, dict):
            rows.append(issue)
    return pd.DataFrame(rows)
