"""Markdown report rendering."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd

from alphalab_agent.config import ResearchConfig
from alphalab_agent.review.checks import ReviewCheck, summarize_review


def render_markdown_report(
    config: ResearchConfig,
    metrics: dict[str, float | int],
    checks: Iterable[ReviewCheck],
    portfolio_returns: pd.DataFrame,
    positions: pd.DataFrame,
) -> str:
    """Render a deterministic Markdown research report."""

    checks = list(checks)
    lines = [
        "# AlphaLab Agent v0.1 Research Report",
        "",
        "## Summary",
        "",
        "This report was generated by deterministic local code using synthetic market data.",
        "It is for engineering demonstration and education only, not investment advice.",
        "",
        f"- Reviewer status: **{summarize_review(checks)}**",
        f"- Rebalance periods: {int(metrics['periods'])}",
        f"- Total return: {_pct(metrics['total_return'])}",
        f"- Annualized return: {_pct(metrics['annualized_return'])}",
        f"- Annualized volatility: {_pct(metrics['annualized_volatility'])}",
        f"- Sharpe: {float(metrics['sharpe']):.2f}",
        f"- Max drawdown: {_pct(metrics['max_drawdown'])}",
        f"- Win rate: {_pct(metrics['win_rate'])}",
        f"- Average turnover: {_pct(metrics['average_turnover'])}",
        f"- Average cost drag: {_pct(metrics['average_cost_drag'])}",
        f"- Total cost drag: {_pct(metrics['total_cost_drag'])}",
        "",
        "## Workflow",
        "",
        "synthetic market data -> panel builder -> factor calculation -> forward return label -> "
        "top-k long-only backtest -> risk metrics -> reviewer checks -> markdown report",
        "",
        "## Research Hypothesis",
        "",
        "A simple composite of momentum, short-horizon reversal, low volatility, and volume trend "
        "can rank a synthetic stock universe for a deterministic top-k long-only research demo.",
        "",
        "## Data Summary",
        "",
        "| Item | Value |",
        "|---|---:|",
        f"| Data source | `synthetic` |",
        f"| Random seed | `{config.seed}` |",
        f"| Start date | `{config.start_date}` |",
        f"| Business days | `{config.n_days}` |",
        f"| Symbols | `{config.n_symbols}` |",
        f"| Forward label horizon | `{config.forward_days}` days |",
        "",
        "## Factor Summary",
        "",
        "| Factor | Weight | Interpretation |",
        "|---|---:|---|",
        f"| momentum_20 | {config.factor_weights.get('momentum_20', 0.0):.2f} | 20-day price momentum |",
        f"| reversal_5 | {config.factor_weights.get('reversal_5', 0.0):.2f} | 5-day mean reversion proxy |",
        f"| low_volatility_20 | {config.factor_weights.get('low_volatility_20', 0.0):.2f} | preference for lower recent volatility |",
        f"| volume_trend_20 | {config.factor_weights.get('volume_trend_20', 0.0):.2f} | 20-day volume trend |",
        "",
        "## Backtest Config",
        "",
        "| Item | Value |",
        "|---|---:|",
        f"| Portfolio rule | `top-{config.top_k} long-only equal weight` |",
        f"| Rebalance interval | `{config.rebalance_every}` business days |",
        f"| Transaction cost | `{config.transaction_cost_bps}` bps per one-way turnover |",
        f"| Annualization | `{config.annualization}` trading days |",
        "",
        "## Risk Metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Periods | {int(metrics['periods'])} |",
        f"| Total return | {_pct(metrics['total_return'])} |",
        f"| Annualized return | {_pct(metrics['annualized_return'])} |",
        f"| Annualized volatility | {_pct(metrics['annualized_volatility'])} |",
        f"| Sharpe | {float(metrics['sharpe']):.2f} |",
        f"| Max drawdown | {_pct(metrics['max_drawdown'])} |",
        f"| Win rate | {_pct(metrics['win_rate'])} |",
        f"| Average turnover | {_pct(metrics['average_turnover'])} |",
        f"| Average cost drag | {_pct(metrics['average_cost_drag'])} |",
        f"| Total cost drag | {_pct(metrics['total_cost_drag'])} |",
        "",
        "## Configuration",
        "",
        "| Parameter | Value |",
        "|---|---:|",
    ]

    for key, value in config.to_dict().items():
        lines.append(f"| `{key}` | `{value}` |")

    lines.extend(
        [
            "",
            "## Reviewer Findings",
            "",
            "| Check | Status | Severity | Message |",
            "|---|---|---|---|",
        ]
    )
    for check in checks:
        lines.append(f"| {check.name} | {check.status} | {check.severity} | {check.message} |")

    lines.extend(["", "## Recent Portfolio Returns", ""])
    lines.append(_frame_to_markdown(portfolio_returns.tail(10)))
    lines.extend(["", "## Recent Positions", ""])
    lines.append(_frame_to_markdown(positions.tail(15)))
    lines.extend(
        [
            "",
            "## Limitations",
            "",
            "- The dataset is synthetic and is designed for reproducibility, not real alpha discovery.",
            "- The backtest is a simple top-k research simulation, not an execution simulator.",
            "- High turnover can make a strategy fragile after realistic costs and constraints.",
            "- v0.1 does not include train/test splits, factor IC analysis, or real market validation.",
            "",
            "## Safety Notes",
            "",
            "- v0.1 does not use real market data APIs.",
            "- v0.1 does not use an LLM.",
            "- v0.1 does not place orders or connect to a broker.",
            "- Results on synthetic data do not imply real-world tradability.",
            "",
            "## Disclaimer",
            "",
            "This report is for engineering demonstration and education only. It is not investment "
            "advice and should not be used to make trading decisions.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_markdown_report(path: Path, markdown: str) -> Path:
    """Write a Markdown report and return the path."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    return path


def _pct(value: float | int) -> str:
    return f"{float(value):.2%}"


def _frame_to_markdown(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "_No rows produced._"
    display = frame.copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(lambda value: f"{value:.6f}")
    display = display.astype(str)
    header = "| " + " | ".join(display.columns) + " |"
    separator = "| " + " | ".join("---" for _ in display.columns) + " |"
    rows = ["| " + " | ".join(row) + " |" for row in display.to_numpy()]
    return "\n".join([header, separator, *rows])
